server:
  port: 7070

spring:
  profiles:
    active: dev
  application:
    name: meta-centre-service
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
        group: centre
    config:
      server:
        git:
          uri: https://github.com/XiFYuW/meta-java
          searchPaths: /meta-centre/auto-centre/client,/meta-centre/auto-centre/chain
          force-pull: true
      discovery:
        service-id: meta-centre-service
