spring:
  application:
    name: meta-centre-client
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
        group: centre
    config:
      discovery:
        enabled: true
